### ISSUE TITLE
Fully support flow.json functionality

### ISSUE THREAD

**Issue by DylanTinianov** [onflow/vscode-cadence#133]
## Instructions

Provide full support for flow.json functionality including:
- Defining custom accounts
- Defining contract file locations
- Defining deployments 

Have the extension parse this file and ask the user if they want to deploy their pre-defined contracts.

Mention: #175

**Comment by jamietdavidson** [comment]
@DylanTinianov, is this on the roadmap to get fixed this querter?

**Comment by sideninja** [comment]
@jamietdavidson we will start the work on it this quarter, and I believe finish as well. It's high on priority list. After new year we again put focus on vscode to make it really work well. Sorry for any inconvenience.

**Comment by sideninja** [comment]
This will be solved in https://github.com/onflow/cadence-tools/pull/52
