### ISSUE TITLE
Cannot find declaration error on import

### ISSUE THREAD

**Issue by jamescharlesworth** [onflow/vscode-cadence#153]
### Problem
Deploying contract and importing it does not work as expected with the interpreter.  After clicking deploy contract I'm expecting I can import it from a transaction script.  The actual result is an error `cannot find declaration PinataPartyContract in f8d6e0586b0a20c7.PinataPartyContract`.

### Steps to Reproduce

Create a Contract like this:
```cdc

pub contract PinataPartyContract {

  pub resource NFT {
    pub let id: UInt64
    init(initID: UInt64) {
      self.id = initID
    }
  }

  pub resource interface NFTReceiver {
    pub fun deposit(token: @NFT, metadata: {String : String})
    pub fun getIDs(): [UInt64]
    pub fun idExists(id: UInt64): Bool
    pub fun getMetadata(id: UInt64) : {String : String}
  }

  pub resource Collection: NFTReceiver {
    pub var ownedNFTs: @{UInt64: NFT}
    pub var metadataObjs: {UInt64: { String : String }}

    init () {
        self.ownedNFTs <- {}
        self.metadataObjs = {}
    }

    pub fun withdraw(withdrawID: UInt64): @NFT {
        let token <- self.ownedNFTs.remove(key: withdrawID)!

        return <-token
    }

    pub fun deposit(token: @NFT, metadata: {String : String}) {
        self.metadataObjs[token.id] = metadata
        self.ownedNFTs[token.id] <-! token
    }

    pub fun idExists(id: UInt64): Bool {
        return self.ownedNFTs[id] != nil
    }

    pub fun getIDs(): [UInt64] {
        return self.ownedNFTs.keys
    }

    pub fun updateMetadata(id: UInt64, metadata: {String: String}) {
        self.metadataObjs[id] = metadata
    }

    pub fun getMetadata(id: UInt64): {String : String} {
        return self.metadataObjs[id]!
    }

    destroy() {
        destroy self.ownedNFTs
    }
  }

  pub fun createEmptyCollection(): @Collection {
      return <- create Collection()
  }

  pub resource NFTMinter {
      pub var idCount: UInt64

      init() {
          self.idCount = 1
      }

      pub fun mintNFT(): @NFT {
          var newNFT <- create NFT(initID: self.idCount)

          self.idCount = self.idCount + 1 as UInt64

          return <-newNFT
      }
  }
  
  init() {
      log("hello world")
      self.account.save(<-self.createEmptyCollection(), to: /storage/NFTCollection)
      self.account.link<&{NFTReceiver}>(/public/NFTReceiver, target: /storage/NFTCollection)
      self.account.save(<-create NFTMinter(), to: /storage/NFTMinter)
  }
}
```
and a transaction like this:
```cdc
import PinataPartyContract from 0xf8d6e0586b0a20c7

transaction {
  let receiverRef: &{PinataPartyContract.NFTReceiver}
  let minterRef: &PinataPartyContract.NFTMinter

  prepare(acct: AuthAccount) {
      self.receiverRef = acct.getCapability<&{PinataPartyContract.NFTReceiver}>(/public/NFTReceiver)
          .borrow()
          ?? panic("Could not borrow receiver reference")        
      
      self.minterRef = acct.borrow<&PinataPartyContract.NFTMinter>(from: /storage/NFTMinter)
          ?? panic("could not borrow minter reference")
  }

  execute {
      let metadata : {String : String} = {
          "name": "The Big Swing",
          "swing_velocity": "29", 
          "swing_angle": "45", 
          "rating": "5",
          "uri": "ipfs://QmRZdc3mAMXpv6Akz9Ekp1y4vDSjazTx2dCQRkxVy1yUj6"
      }
      let newNFT <- self.minterRef.mintNFT()
  
      self.receiverRef.deposit(token: <-newNFT, metadata: metadata)

      log("NFT Minted and deposited to Account 2's Collection")
  }
}
```

Click the Deploy Contract PinataPartContract to ServiceAccount Link:
![Screen Shot 2022-08-20 at 5 17 05 PM](https://user-images.githubusercontent.com/666455/185766407-b00b3354-7f4e-4f31-ac64-e28e5fcea724.png)
I get a tooltip in the bottom right, but nothing in the logs that im expecting from the init method of the contract - i logged" hello world" but its not there.

Switch to the transaction and it cant find the contract:
![Screen Shot 2022-08-20 at 5 25 53 PM](https://user-images.githubusercontent.com/666455/185766460-b0bd749c-2f6e-464c-a66a-80d87f3637cf.png)

additionally if i run `flow accounts get 0xf8d6e0586b0a20c7` the output is
```
➜  pinata-party flow accounts get 0xf8d6e0586b0a20c7

Address  0xf8d6e0586b0a20c7
Balance  999999999.99700000
Keys     1

Key 0   Public Key               3ae9148d3cc6eecba7e0bf8534478d8449acca80a8cd9adb4379447cc123db189aade01daed99fe77f790f0859188f25fa9d972743d23875eee091034964be00
        Weight                   1000
        Signature Algorithm      ECDSA_P256
        Hash Algorithm           SHA3_256
        Revoked                  false
        Sequence Number          0
        Index                    0

Contracts Deployed: 10
Contract: 'FlowClusterQC'
Contract: 'FlowContractAudits'
Contract: 'LockedTokens'
Contract: 'FlowEpoch'
Contract: 'FlowIDTableStaking'
Contract: 'FlowStakingCollection'
Contract: 'FlowServiceAccount'
Contract: 'StakingProxy'
Contract: 'FlowDKG'
Contract: 'FlowStorageFees'
```
No `PinataPartyContract` contract ^^^ however if i manually deploy the contract i can see it:
![Screen Shot 2022-08-20 at 5 30 46 PM](https://user-images.githubusercontent.com/666455/185766632-629ae233-1f00-4efa-8e91-e4f7f33e5007.png)

Also i notice that importing something like FlowEpoch from 0xf8d6e0586b0a20c7 seems to work. It feels like it could be a deployment issue and/or cache issue of contracts being deployed manually not getting picked up by the interpreter. I suspect its not really deploying when i click the extension link in visual studio because when i manually deploy using the command line I see logs reflecting what i expect.

### Acceptance Criteria

The interpreter should load the deployed contact.

### Context

I'm following this tutorial here https://medium.com/pinata/how-to-create-nfts-like-nba-top-shot-with-flow-and-ipfs-701296944bf

Also this is my flow.json (with key removed, not sure if thats needed for security reasons or not)
```json
{
	"networks": {
		"emulator": "127.0.0.1:3569",
		"mainnet": "access.mainnet.nodes.onflow.org:9000",
		"testnet": "access.devnet.nodes.onflow.org:9000"
	},
	"accounts": {
		"emulator-account": {
			"address": "f8d6e0586b0a20c7",
			"key": "<REMOVED>"
		}
	},
	"contracts": {
		"PinataPartyContract": "./cadence/contracts/PinataPartyContract.cdc"
   },
   "deployments": {
		"emulator": {
			"emulator-account": ["PinataPartyContract"]
		}
	}
} 
```

**Comment by bluesign** [comment]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/1119338/185800981-d506c71b-ae4c-428f-a2d9-b5196b0a36d4.png">

**Comment by jamescharlesworth** [comment]
sorry for the confusion, that i think was left around from me trying different things. i switch to Alice account (01cf0e2f2f715450) in vs code to try that. If you just use the service account the dialog has the correct account but nothing in the logs:
![Screen Shot 2022-08-21 at 1 49 19 PM](https://user-images.githubusercontent.com/666455/185804247-622021f3-346a-4d7c-a5fe-1fcf2d2a0949.png)

**Comment by jamietdavidson** [comment]
Experiencing the same problem. It appears to me as though the cadence language server is spinning up an emulator in some far off land that we're not privy to.

**Comment by sideninja** [comment]
This should now be solved. Cadence extension allows you running your own emulator instance and it will connect to it if present, otherwise it will start its own hosted version. Resolving should work fine as well.
