### ISSUE TITLE
Publish extension on Open VSX

### ISSUE THREAD

**Issue by dreamsmasher** [onflow/vscode-cadence#167]
### Issue To Be Solved

Currently, the vscode-cadence extension is only published on the Visual Studio Marketplace. This is where most users get their extensions, but there are other editors like VSCodium that also make use of VSIX extensions without being tied down to Microsoft's ecosystem. The alternative marketplace, Open VSX, is meant to be an open-source, vendor neutral registry for VSIX extensions. There's a sizeable amount of users who use telemetry-free alternatives to VSCode and would appreciate an Open VSX release of the Cadence extension. 

### (Optional): Suggest A Solution

Add an extra step to CI that publishes the built VSIX bundle to Open VSX, in addition to the Visual Studio marketplace. Open VSX has a repository with scripts for this exact purpose: https://github.com/open-vsx/publish-extensions

**Comment by DylanTinianov** [comment]
Done!
