### ISSUE TITLE
langauge server will not start on flow-cli later then  0.39.1

### ISSUE THREAD

**Issue by bjartek** [onflow/vscode-cadence#174]
When starting my editor (nvim) with flow-cli versions later then 0.39.1 my editor just hangs and will not start lsp.

**Comment by DylanTinianov** [comment]
> flow-cli version 0.39.1 , 0.39.2 and 0.39.3 does not work on vscode either. The flow-cli dependency cannot be found on vscode.
> 
> Also inline comment and auto-complete seems to be gone as well for these flow-cli versions.

@Bamthelearner is your flow-cli installed globally and you can access it by typing "flow version" in a command line?

**Comment by Bamthelearner** [comment]
yes. I can confirm that it is installed globally. 
Now I am at v0.39.3

**Comment by bjartek** [comment]
This is the one i use, not sure if you have contact with the maintainer or not https://github.com/Lucklyric/coc-cadence
