### ISSUE TITLE
Better integration with local dev environment (vscode + flow cli)

### ISSUE THREAD

**Issue by muttoni** [onflow/vscode-cadence#178]
### Issue To Be Solved

It seems like the vscode extension runs its own emulator with handy shortcuts like “deploy contract to Alice” or “execute script”, but:
- it’s unclear how to handle the two emulator environments in parallel? Are they completely independent? for example, if I open vscode, the extension says “flow emulator connected”, regardless of whether I run a flow cli emulator or not, likewise, nothing changes in the extension when I run a regular cli emulator.
- contract deployments work great (e.g. deploy contract to Alice), but then what? for example with tx’s the “send transaction” button disappears if there are arguments.  how can I interact with the vscode emulator via the cli?
what is the correct flow.json setup to have the vscode extension properly run scripts that reference a deployed contract? - for example, my contract is deployed to the service account in my regular flow cli setup, but there’s no way to deploy to the service account via the vscode extension (only alice, bob, charlie, dave, etc), so when I try to execute the script, it throws an error
- in general, it’s a little confusing that the vscode emulator is separate from the flow cli one imo. any plans to select what emulator to point to? e.g. i run an emulator instance via flow emulator and then point my vscode extension to it. If it’s already possible, how can I do it?
- the vscode extension breaks vscode's native bracket autofilling and coloring

p.s. it would be great to have more info/docs here: [https://developers.flow.com/tools/vscode-extension/index](https://developers.flow.com/tools/vscode-extension/index) which hasn’t been updated since Jan 2021!
and github docs are also a year old: [https://github.com/onflow/vscode-cadence/blob/master/docs/overview.md](https://github.com/onflow/vscode-cadence/blob/master/docs/overview.md)

### (Optional): Suggest A Solution

- Generally better interoperability between Flow CLI and VSCode extension, including auto-resolving imports based on flow.json
- Better inspection of output throughout
- Ability to specify args in tx's via a UI, as well as inspect storage and general account state

### (Optional): Context

Initial feedback from @sideninja :

> it’s unclear how to handle the two emulator environments in parallel? Are they completely independent? for example, if I open vscode, the extension says “flow emulator connected”, regardless of whether I run a flow cli emulator or not, likewise, nothing changes in the extension when I run a regular cli emulator.

They are now completely independent, that was intentionally changed since before this caused a lot of issues with out of sync states, and maybe emulator crashing etc. This won’t change back. 

> contract deployments work great (e.g. deploy contract to Alice), but then what? for example with tx’s the “send transaction” button disappears if there are arguments.  how can I interact with the vscode emulator via the cli?

You can use transaction with arguments but you must provide pragma comment saying what arguments are - example would be: `/// pragma signers Alice,Bob` for defining multiple signers or `/// pragma arguments  (v: "test 12")` for argument, this is nowhere documented and it should be and will be.

> what is the correct flow.json setup to have the vscode extension properly run scripts that reference a deployed contract? (see screenshot below) - for example, my contract is deployed to the service account in my regular flow cli setup, but there’s no way to deploy to the service account via the vscode extension (only alice, bob, charlie, dave, etc), so when I try to execute the script, it throws an error

why do you want to deploy to service account and not alice?

(answer: mainly out of habit and convenience, since it's the default emulator-account created on flow init

> in general, it’s a little confusing that the vscode emulator is separate from the flow cli one imo. any plans to select what emulator to point to? e.g. i run an emulator instance via flow emulator and then point my vscode extension to it. If it’s already possible, how can I do it?

No plans, as said due to reasons above. But it would be nice to expose emulator that is hosted in vscode to the outside world via an API, so you can use CLI against the emulator run by vscode.

**Comment by sideninja** [comment]
One important point from the above feedback is interoperability between the CLI and vscode-hosted emulator. Although I still believe vscode handling emulator is better due to sync issues if that's not the case, it would need to expose access to it. In the next version we should introduce an emulator management section, where you will be able to see all the emulator logs, will be able to see the connection address you will be able to use to connect to it from other tools like CLI, you will be able to enable persistence of state and reset the state.

**Comment by bluesign** [comment]
> One important point from the above feedback is interoperability between the CLI and vscode-hosted emulator.

I think more importantly, interoperability with `extension` and any `network`. I think I may somehow understand extension managing an emulator, but extension only allowing connection to that network does not make any sense. 

For playground it is ok, but now converting full development environment ( vs-code ) to playground with extension is good in my opinion.

**Comment by sideninja** [comment]
That could be an advanced option, but first we want to make sure vscode is easy to use for common usage and then add these advanced features in.

**Comment by reas0n** [comment]
has any progress been made on this? I'm a total noob to most of this and I'm not really sure how to get around the issue.

**Comment by sideninja** [comment]
Unfortunately not yet, but we are planning to work on this soon. Apologies for issues. 

@reas0n the way you can use it is to start up your own emulator using CLI `flow emulator` and then just make sure your project is manually deployed there. I'm completely aware this is not good UX and we are working on a solution already but it will take a bit of time.

**Comment by jamietdavidson** [comment]
This is related to both https://github.com/onflow/vscode-cadence/issues/175 and https://github.com/onflow/vscode-cadence/issues/133. I've been following this for a while, seems to be a pressing issue for a handful of developers i've spoken to developing on Flow. 

Please get it fixed team! :)

**Comment by sideninja** [comment]
@jamietdavidson yep, starting the new year it will have our focus. Also some other cool features coming out that will make vscode great.

**Comment by DylanTinianov** [comment]
VSCode will no longer host its own emulator but instead connect to a locally running emulator (https://github.com/onflow/vscode-cadence/pull/243)
