### ISSUE TITLE
Cadence VSCode extension conflicts with VSCode bracket colorization

### ISSUE THREAD

**Issue by muttoni** [onflow/vscode-cadence#181]
### Problem

Bracket colorization is not respected when editing Cadence files. 

i.e. 

```
   "editor.guides.bracketPairs": true,
   "editor.bracketPairColorization.enabled": true,
```

### Steps to Reproduce
Open any .cdc file:

<img width="705" alt="image" src="https://user-images.githubusercontent.com/27052451/192533000-d2c45f7b-8f0c-4241-93d6-08effbc3a460.png">

You'll notice brackets are not highlighted, nor colored.

Expected result (taken from a non-cdc file):

<img width="654" alt="image" src="https://user-images.githubusercontent.com/27052451/192533145-5cc9e193-6643-45c7-96fb-a431816b7055.png">

### Acceptance Criteria

Brackets should be colorized.

### Context

VSCode extension version: v1.0.4

Other system info:

```
  System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 105.42 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.15.1 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Managers:
    Homebrew: 3.6.1 - /opt/homebrew/bin/brew
    pip3: 22.2.2 - /opt/homebrew/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 13.1.6 - /usr/bin/gcc
    Git: 2.34.0 - /opt/homebrew/bin/git
    Clang: 13.1.6 - /usr/bin/clang
    FFmpeg: 5.1 - /opt/homebrew/bin/ffmpeg
  Servers:
    Apache: 2.4.48 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.11 - /usr/local/bin/docker
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.71.2 - /usr/local/bin/code
    Vim: 8.2 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
```

**Comment by turbolent** [comment]
We probably need to tokenize the braces as special tokens. Maybe use the scope inspector (https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#textmate-tokens-and-scopes) to look at a file (JS?) where it works and see how it differs.

This seems like a very low priority issue though.
