### ISSUE TITLE
False "checked of imported program `X.cdc` failed" error

### ISSUE THREAD

**Issue by alilloig** [onflow/vscode-cadence#183]
### Problem

When you introduce a correct import at the beginning of a Cadence file, in some situations it reports that error while the line is currently ok

### Steps to Reproduce
Type the import (I have actually reproduced the bug cutting/pasting the line) if you press Intro it will trigger the error. If you simply move the cursor to other place by clicking the error won't trigger.

<img width="424" alt="Screenshot 2022-10-13 at 17 07 32" src="https://user-images.githubusercontent.com/6607145/195635106-085ef3a5-1130-4143-a9b4-d0e8c7016e4c.png">
<img width="416" alt="Screenshot 2022-10-13 at 17 07 44" src="https://user-images.githubusercontent.com/6607145/195635123-4baa7029-eab8-4033-b32a-f6061fb922d1.png">

**Comment by alilloig** [comment]
Actually even if you skip to press Intro, the moment you try to use "something" from that contract (In this case, when I made a resource conformant to a resource interface defined on the imported contract) the language server pops again the error, and consequently says that it can find the types I want to use.

**Comment by turbolent** [comment]
@alilloig Can you please provide some more details: 
- What version of the Flow CLI and VS Code extension are you using?
- Can you please share the code that is producing the error? (import and importing code)

**Comment by alilloig** [comment]
Sorry for the late response, this got lost between my notifications!!

I just realised I totally miss explained the issue here. I was doing a circular dependency, which can not happen in flow (I was trying to make NonFungibleToken to import MetadataViews, which imports NonFungibleToken by itself).

Right now I can not get the vs code to tell me that the import is correct (which was causing me a little confusion). I don't know if it would be possible for the LS or the vs code extension to understand that the user is trying to create a circular dependency and point it out to the developer, but that would be great.
