### ISSUE TITLE
Cannot resolve imports on Windows

### ISSUE THREAD

**Issue by DylanTinianov** [onflow/vscode-cadence#224]
### Instructions

The language server is not able to resolve import on Windows. 
This is likely caused by the incorrect path string being passed to the language server, similar to the previous codelens issue.

<img width="809" alt="Screen Shot 2023-01-13 at 1 03 45 PM" src="https://user-images.githubusercontent.com/19377621/212389301-b0ab1753-d9e6-4a24-9a69-7dbc79423a95.png">
<img width="697" alt="Screen Shot 2023-01-13 at 1 03 34 PM" src="https://user-images.githubusercontent.com/19377621/212389304-428d1ece-d5ec-45bc-aac9-7aea33aceb3a.png">

**Comment by sideninja** [comment]
Can you try adding the contract to flow.json?

**Comment by sideninja** [comment]
Will fix this on Monday.
