### ISSUE TITLE
support access(account) functions

### ISSUE THREAD

**Issue by bz-hashtag-0780** [onflow/vscode-cadence#233]
### Problem

When a contract has access(account) function it gives an error which also makes it difficult to write transactions and scripts as they will not be able to use the smart contract that has the access(account) function. Trying to turn the flagg off in vscode doesn't work (also restarted still doesn't work)

**Comment by sideninja** [comment]
Thank you for reporting will look into this.

**Comment by bz-hashtag-0780** [comment]
Cadence VScode extension version: v1.0.6
OS: MacOS
Flow CLI:  v0.43.3
<img width="1113" alt="Screenshot 2023-01-19 at 19 10 35" src="https://user-images.githubusercontent.com/88026162/213525941-4f3cabc4-76ba-48ae-9769-b0c38bce3302.png">
<img width="724" alt="Screenshot 2023-01-19 at 19 11 01" src="https://user-images.githubusercontent.com/88026162/213526021-b8179f2c-b3e8-45b1-9eb5-42af1f2819d2.png">

**Comment by sideninja** [comment]
Hey @bz-hashtag-0780 you are right and I have the PRs already in, will release Monday, which will make setting the mode work but also make the checking correct based on the flow.json. 
https://github.com/onflow/vscode-cadence/pull/235
https://github.com/onflow/cadence-tools/pull/69
