### ISSUE TITLE
Allow addresses generated by fcl to show as accounts to switch to in vscode

### ISSUE THREAD

**Issue by alxocity** [onflow/vscode-cadence#26]
### Issue To Be Solved

Allow addresses generated by fcl to show as accounts to switch to in vscode. This will make dApp development easier if you can login to the fcl wallet, then have that new account available in the emulator to manually run transactions from vscode as that account.

**Comment by bthaile** [comment]
The vision for vscode extension is to allow more extensions to built on top of vscode ext. Closing
