### ISSUE TITLE
Issue: Not all dependencies are installed: Flow CLI

### ISSUE THREAD

**Issue by aeither** [onflow/vscode-cadence#279]
### Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

Installing cadence vscode extension. Most of the features does not work (debugging, deploy, code generation ...) It shows that "Not all dependencies are installed: Flow CLI". 

### Steps to Reproduce

arch -arm64 brew install flow-cli
install cadence extension from vscode extensions  

### Acceptance Criteria

<if any>

### Context

I'm following the docs to deploy a contract on testnet. I wanted a better dev experience with the extension to have code generation and deploy

**Comment by sideninja** [comment]
@aeither thank you for reporting.
@DylanTinianov can you take a look at this?

**Comment by aeither** [comment]
I have flow-cli version
❯ flow version
Version: v0.46.2

Cadence v1.2.0

The extension can't install flow-cli.

**Comment by jribbink** [comment]
I'm suddenly running into this too after updating to MacOS Ventura.  Doesn't look like NodeJS spawn is resolving my $PATH properly as it's saying `flow: command not found` in the debug console.

**Comment by jribbink** [comment]
This should be solved by #351
