### ISSUE TITLE
Report conversions from Playground

### ISSUE THREAD

**Issue by DylanTinianov** [onflow/vscode-cadence#307]
## Instructions

Report to Mixpanel when a project exported from playground is opened in vscode for the first time by that vscode user.
- Maintain a list of exported playground projects in the user's vscode settings where we store the user id.

Playground will export the following:
![image (2)](https://user-images.githubusercontent.com/19377621/235495355-ee0f4160-f31a-487a-853d-1d6f0c33a220.png)

Also report when an exported project has an initial deployment on emulator. In order to accomplish this, we might need to report this on the emulator / flow-cli side instead of VSCode (especially if users are using flow dev instead of vscode commands).

**Comment by sideninja** [comment]
Let's make sure there's an opt-out option on the playground export dialog. Also, make sure to explain what we track. We shouldn't do this without explaining it to the user. cc @fotescodev @bthaile
