### ISSUE TITLE
Custom flow.json locations do not work

### ISSUE THREAD

**Issue by jribbink** [onflow/vscode-cadence#316]
### Problem

I am unable to connect to the flow emulator when specifying a custom flow.json location.  It looks like within the `verifyEmulator` function `flowJsonPrivKey === undefined` & `verifyEmulator` returns false.  I think this probably broke around the time of https://github.com/onflow/vscode-cadence/pull/243 since we refactored how the emulator is connected.

https://github.com/onflow/vscode-cadence/blob/67ce76078b9b22e120eb13131c678425738ce12d/extension/src/emulator/local/emulatorScanner.ts#L18-L22

### Steps to Reproduce

 1. Create a subfolder with your flow.json in it
 2. Specify the absolute path of the flow.json
 3. Run the emulator
 4. The emulator will not be connected to VSCode extension.

### Acceptance Criteria

Emulator connects to a custom flow.json location.

**Comment by DylanTinianov** [comment]
Have you tried running the emulator in the same folder as your custom flow.json path. Then it should be able to connect, seems to be working for me.

**Comment by jribbink** [comment]
> Have you tried running the emulator in the same folder as your custom flow.json path? It should be able to connect, seems to be working for me.

Haha my bad, I was accidentally using the bad kitty-items flow.json as per #313 🤦‍♂️
