### ISSUE TITLE
Extension not recognizing attachments syntax

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/vscode-cadence#320]
### Problem

Attachments enabled in [emulator v0.47.0](https://github.com/onflow/flow-emulator/releases/tag/v0.47.0), but the extension doesn't support the feature. Not sure whether to label this as bug or enhancement since attachments are a new Cadence feature.

### Steps to Reproduce

Define an attachment and see the following error:

<img width="634" alt="Screenshot 2023-05-14 at 12 02 35 PM" src="https://github.com/onflow/vscode-cadence/assets/108043524/bbf57ba7-25c7-4ff1-a3b5-4baf7ef271c2">

### Acceptance Criteria

Attachments and related syntax recognized and supported by the extension.

### Context

Working on a tutorial covering attachments.

**Comment by sideninja** [comment]
Thank you for reporting. We will tag accordingly.

**Comment by jribbink** [comment]
This is a language server issue and covered in https://github.com/onflow/cadence-tools/pull/118
