### ISSUE TITLE
Alias account addresses

### ISSUE THREAD

**Issue by 10thfloor** [onflow/vscode-cadence#34]
From https://forum.onflow.org/t/typical-dapp-project-structure/814/7

"Right now the tooling in vscode has to have hard coded address imto the contracts to work properly. However that scales poorly to a model where the accounts are different on emulator/testnet/mainnet. So can the vscode extension get support for a lookup of an account from an alias or something?"

**Comment by spacepluk** [comment]
Any solutions/workarounds for this?

**Comment by spacepluk** [comment]
Thanks! I'm just starting out with flow.  What's the ETA usually for this kind of change/proposal to make it into the release?

**Comment by spacepluk** [comment]
Thanks @sideninja! nah that's alright! I just wanted to know a rough estimate :)

In the meantime I can just mimic the string replacement solution that is used in the examples.
But knowing that a fix is coming I won't spend a lot of time on it :)
