### ISSUE TITLE
Where are Alice's, Bob's and Charlie's keys ?

### ISSUE THREAD

**Issue by cybercent** [onflow/vscode-cadence#347]
### Instructions
 After installing the Flow CLI and the VS code extension, VSCode presents the user the ability to deploy a contract to Alice.

Who is Alice ?
Alice's account is not defined in the `flow.json` file.
If Alice, Bob, and Charlie were create by default, where are there private keys?

The VS Code extension, allows the creation on new accounts.
I just created Eve but where is Eve's key?

I can't send a transaction with `flow transaction send` as Eve's key is not in the `flow.json`.
It appears that one can't send transactions with arguments from the VS Code extension.

I opened the same issue on Flow CLI as @sideninja marked a similar issue solved and mentioned this should be possible.
https://github.com/onflow/flow-cli/issues/1055

**Comment by jribbink** [comment]
Thanks for opening an issue for this, I was actually going to create on for the same thing.  Like you pointed out, it doesn't really make sense to have different accounts in the VSCode extension compared to what exists in the flow.json.  I'll see what I can do to sync these up.
