### ISSUE TITLE
Attach to a running emulator

### ISSUE THREAD

**Issue by pdahlberg** [onflow/vscode-cadence#38]
### Issue To Be Solved

Let VS Code attach to an emulator started in the terminal.

**Comment by MaxStalker** [comment]
@psiemens we shall utilize local `flow.json` file instead of reading service account from `cadence` namespace in VS Code config. Would also allow enable better account management.

**Comment by DylanTinianov** [comment]
The emulator is moving into the language server instead of running locally in a terminal. However, we will soon introduce the ability to load snapshots of a previous emulator state (including account data/ etc).

**Comment by bluesign** [comment]
@DylanTinianov does this mean we cannot use external emulator with VSCode anymore?
