### ISSUE TITLE
Flow Emulator Error

### ISSUE THREAD

**Issue by ArcadEd** [onflow/vscode-cadence#39]
I'm trying to get the Flow emulator going in VS Code.   I'm copying some of the code from the playground tutorial.  Just the HelloWorlds.cdc and Transaction1.  Deploying HelloWorld to the test account works fine, but when trying to submit the transaction to the test account I keep getting 
"[Error - 11:08:46 PM] Request workspace/executeCommand failed. Message: client: rpc error: code = Internal desc = failed to encode value: unsupported value: <nil>, <nil> Code: -32603"

**Comment by turbolent** [comment]
@ArcadEd Could you please re-try with the latest version of the CLI and the extension? See the installation instructions here https://github.com/onflow/vscode-cadence#installation
