### ISSUE TITLE
Capabilities API labeled deprecated but Capability Controllers aren't yet on m

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/vscode-cadence#400]
### Problem

The Capabilities API is planned to be deprecated in favor of Capability Controllers (CapCons), but CapCons are not yet live on Mainnet and VS Code extension notifies devs that the existing Capability API is deprecated.

A dev following the instructions presented would find a lack of documentation on the suggested API and be frustrated to find out that the API they implemented isn't yet supported on Mainnet.

### Steps to Reproduce

1. Run emulator
2. Attempt to retrieve a Capability using the existing API

<img width="641" alt="Screenshot 2023-07-20 at 2 16 36 PM" src="https://github.com/onflow/vscode-cadence/assets/108043524/c3cff5b6-5442-4eb4-b492-d89a5ef88ce5">

### Acceptance Criteria

The notice is removed until CapCons are live on Mainnet at which point the plan is to support a transition period between APIs and the deprecation notice would be appropriate.

### Context

Originally thought CapCons were a blocker for Mainnet deployment, but realized the feature is not yet supported.

**Comment by m-Peter** [comment]
I will have a shot at this :pray:

**Comment by m-Peter** [comment]
There are some more functions that have the same issue, that is described above. E.g:

![capability-api-deprecations](https://github.com/onflow/vscode-cadence/assets/1778965/716fada4-7d55-4cb2-b1da-4cf00fd11ac5)

**Comment by m-Peter** [comment]
Opened a PR to address this: https://github.com/onflow/cadence/pull/2673
