### ISSUE TITLE
Not Compatible with Stable Cadence

### ISSUE THREAD

**Issue by jacob-tucker** [onflow/vscode-cadence#446]
### Problem

VSCode Cadence extension is not compatible with Stable Cadence. Flow CLI v `v1.5.0-stable-cadence.2`. Commit `4e0bfefc19fa72423bb3761c33f763022747cb87`

### Steps to Reproduce

Install latest preview build found here: https://forum.onflow.org/t/update-on-cadence-1-0/5197/6?u=tsnakejake

Try to open VSCode and use the Cadence extension. You will see this error:

![image](https://github.com/onflow/vscode-cadence/assets/15198786/1d81ed06-9bfc-486e-9d19-f81bdc647022)

### Context

Trying to test out new Stable Cadence features with live diagnostic / compile errors and syntax highlighting but am not able to do so.

**Comment by turbolent** [comment]
cc @SupunS

**Comment by jribbink** [comment]
I'll take a look at this today 👍
