### ISSUE TITLE
The plugin cannot connect to the Emulator when private key in file mode with `cadence.customConfigPath` not project root

### ISSUE THREAD

**Issue by btspoony** [onflow/vscode-cadence#465]
### Problem

https://discord.com/channels/613813861610684416/1169205586496331836/1169579486229041259
When I set the private key of emulator-account to `key: { "type": "file", "location": "./emulator.key"}`
the Cadence VSCode plugin cannot connect to the Emulator properly. 
It must be changed to  `key: "{privatekey}"` in order to let the plugin work correctly.
In the project settings, there is a `.vscode/setting.json` file, and `cadence.customConfigPath` is configured for flow.json instead of being in the root directory.

### Steps to Reproduce

1. place the flow project in a subfolder instead of the root directory and set the `cadence.customConfigPath`
2. change the private key of emulator-account to `key: { "type": "file", "location": "./emulator.key"}`
3. create an `emulator.key` file including the private key
4. start emulator, can start normally..
5. the plugin will not be connnected.
6. change the key to `key: "{privateKey}"`
7. restart language service, the plugin will be working.

### Acceptance Criteria

The plugin works well.

### Context

https://discord.com/channels/613813861610684416/1169205586496331836/1169579486229041259

**Comment by jribbink** [comment]
This will no longer be an issue when the emulator connection is removed https://github.com/onflow/vscode-cadence/pull/466
