### ISSUE TITLE
Fail on Flow CLI config creation

### ISSUE THREAD

**Issue by uhbif19** [onflow/vscode-cadence#54]
### Problem

Extension fails on activation.

### Steps to Reproduce

Installed like this `flow cadence install-vscode-extension`.

This appeared, I clicked.

![screenshot 265](https://user-images.githubusercontent.com/300919/124176279-61d2b000-dab7-11eb-87a0-b8a47636c464.jpg)

Got this:

![image](https://user-images.githubusercontent.com/300919/124176169-38b21f80-dab7-11eb-9d9e-c4714678fb96.png)

**Comment by turbolent** [comment]
@uhbif19 Do you have the Flow CLI installed, as noted in the installation instructions? 

Also, could you please provide more details about your environment? What version of the CLI are you using, what OS are you using, etc?

**Comment by uhbif19** [comment]
@turbolent 

```
.venv ❯ flow version                                   
Version: v0.25.0
Commit: 9afd7938ebf603611d7b159278a259c850e0adda
❯ code --version
1.56.2
054a9295330880ed74ceaedda236253b4f39a335
x64

```

Flow CLI was updated from lower version with your sh script, as prescribed in installation instruction. OS is Arch Linux.

**Comment by uhbif19** [comment]
@turbolent 

Also, link to marketplace on README not working: https://marketplace.visualstudio.com/items?itemName=DapperLabs.cadence

**Comment by DylanTinianov** [comment]
I believe this is solved now?
