### ISSUE TITLE
Contracts under `dependencies` fields cannot be properly loaded when config them in `deployment` fields.

### ISSUE THREAD

**Issue by btspoony** [onflow/vscode-cadence#542]
### Instructions

If the contract only exists in the `dependencies` field and not in the `contracts` field of `flow.json`, when it is configured in the `deployment` field, the vscode plugin will report an error and language server will be broken.

### Problem

The language server will be broken with a error thrown.

### Steps to Reproduce

<img width="462" alt="image" src="https://github.com/onflow/vscode-cadence/assets/707025/048191d7-f050-418d-88af-d2d5eee21e53">

### Acceptance Criteria

contracts in the `dependencies` field can be add to `deployment` field and no error occurs.

### Context

VSCode plugin: v2.2.1
flow-cli: v1.13.2

**Comment by btspoony** [comment]
There is another issue, if dependencies are not configured in the `contracts` field. 
An importing error will be reported.
<img width="503" alt="image" src="https://github.com/onflow/vscode-cadence/assets/707025/c7bb3e60-4eff-485d-ad3c-00918b4e9ecb">
After adding all dependencies to the `contracts` field, then it works.
<img width="673" alt="image" src="https://github.com/onflow/vscode-cadence/assets/707025/c87cd79c-2248-4e26-8926-481127dabc89">
<img width="230" alt="image" src="https://github.com/onflow/vscode-cadence/assets/707025/4efad877-850c-40a1-9993-9a6f2e18c4c3">

**Comment by jribbink** [comment]
Is this still an issue in the latest version of the Flow CLI (I can't reproduce it on `v1.18.0`)?  We had an issue where the Cadence Language server was using an outdated version of flowkit (which meant in turn that dependency manager didn't work in the LS).

But I believe this issue should be fixed now.

**Comment by btspoony** [comment]
Yeah, it is fixed now.
I removed all duplicated contracts in `contracts` fields. and it works.

**Comment by btspoony** [comment]
fixed after https://github.com/onflow/flow-cli/releases/tag/v1.18.0
