### ISSUE TITLE
Can't run emulator / no flow init prompt when file is opened

### ISSUE THREAD

**Issue by Guisong-Fu** [onflow/vscode-cadence#55]
Hi all, I upgraded flow-cli to the latest 0.24.1, while the error still remains~ Language Server still cannot be started, emulator cannot be started from the extension. 

```
[Error - 7:07:21 AM] Server initialization failed.
  Message: initialization options: invalid emulator state
  Code: -32603 
```

I have also tried to uninstall the extension from VS Code first and then install again by `flow cadence install-vscode-extension` so to make sure I'm having the latest extension version. But it didn't help, and the version of the cadence extension remains the same which is `0.5.0` ~

**Comment by turbolent** [comment]
I think the problem is here: https://github.com/onflow/vscode-cadence/blob/107abfd0fb79368ea2381add7639318c3628dc63/src/extension.ts#L102-L107

I don't yet know how one could get the directory of the open file if it is not in a workspace.

**Comment by DylanTinianov** [comment]
Won't be relevant when emulator is hosted on the language server in the next release
