### ISSUE TITLE
Extension configured with malformed path when discovering flow.json in workspace

### ISSUE THREAD

**Issue by fluxium** [onflow/vscode-cadence#57]
#### VSCode
Version: 1.58.2 (system setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

#### Flow
flow-cli:
Version: v0.26.0
Commit: 87011245afd3fb98ebab2533cc05e1d5a56410e5

vscode-cadence: 
Version: 0.6.3

### Problem
When opening a cadence file (triggering the language server to start), an error occurs stating the filename, directory name, or volume label syntax is incorrect for the file flow.json.

![cls-bad-path](https://user-images.githubusercontent.com/5983328/128425374-daf59e11-e61e-4a57-abdf-c94e5093287a.png)

When starting the flow emulator using the status bar or command palette the statement passed to the terminal includes the same malformed path:

`flow project start-emulator --config-path=/c:/Source/.../kitty-items/flow.json --verbose`

In this example, the kitty-items repo is opened as a folder/workspace in vscode.

### Possible solution

Changing the following line to use the `fsPath` attribute (rather than the `path` attribute) on the `Uri` object, seems to have corrected this issue in my test environment.

https://github.com/onflow/vscode-cadence/blob/4c3f06fedc649da4a65a519c1fd38c8fe226aa8c/src/config.ts#L42

### Context

Currently working on setting up flow developer workstation and reviewing example code from various repos.

**Comment by eburnette** [comment]
This should be fixed by that pr, can you verify it works for you @fluxium ?

**Comment by dazhilang018900** [comment]
failed to load contract code: /c:/Users/root/learnflow/HelloWorld.cdc: &fs.PathError{Op:"open", 
Path:"/c:/Users/root/learnflow/HelloWorld.cdc", Err:0x7b}

**Comment by dazhilang018900** [comment]
hi, seems there is a new bug here when i deploy the contract to an account

**Comment by dazhilang018900** [comment]
i tried to find .path ,there is no result

**Comment by dazhilang018900** [comment]
i found this code in out/main.js   ,  f=c.fsPath.replace(/\\/g,"/");

**Comment by dazhilang018900** [comment]
![image](https://user-images.githubusercontent.com/16031711/142238318-7519e4d1-21a3-4309-9328-b652d66f5569.png)

**Comment by dazhilang018900** [comment]
i removed the replace function in the main.js , and repack vsix (did not regenerate the main.js file), but the error still happend

**Comment by dazhilang018900** [comment]
please , anyone can help me?

**Comment by dazhilang018900** [comment]
@eburnette

**Comment by eburnette** [comment]
I don't think it's related to the original report. If it's a new bug I suggest opening a new github issue.
