### ISSUE TITLE
Multiple cadence servers started(Multiple problem reports, emulators, etc.)

### ISSUE THREAD

**Issue by MostyXS** [onflow/vscode-cadence#66]
### Problem
When I  often using cadence server restart it start multiple servers I guess, or opens multiple connections

### Steps to Reproduce

Bind restart cadence server on button and spam it
![image](https://user-images.githubusercontent.com/61842968/132850332-151e05fd-9b3c-4943-9ab5-a817e904fa68.png)

**Comment by DylanTinianov** [comment]
I think this bug is fixed in the newest updates. It's not released to the marketplace yet, but will be soon.
