### ISSUE TITLE
Cannot find declaration `AccountManager` in `01cf0e2f2f715450.AccountManager`

### ISSUE THREAD

**Issue by mrakus7** [onflow/vscode-cadence#69]
### Instructions

VSCode Version: 1.62.2
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:51:30.084Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.10.0-9-amd64 

Cadence plugin:
v 0.6.3 (from VSCode repository)
Released on
6/30/2021, 02:18:35
Last updated
6/30/2021, 02:20:51
Identifier
onflow.cadence

### Problem

Cannot find declaration `AccountManager` in `01cf0e2f2f715450.AccountManager`

### Steps to Reproduce

1. Run Flow Emulator from VSCode
2.  Deploy my contract via ServiceAccount
3. Change Account from f8d6e0586b0a20c7 to 01cf0e2f2f715450 
4. Make transaction for Setup Account 
5. During change account back to ServiceAccount there is error (see full log below):

:~/.config/Code/User/workspaceStorage/5f282822a868295631512e3613680733/onflow.cadence$ flow project start-emulator --config-path=/home/user/flow/playground/flow.json --verbose
⚠️  DEPRECATION WARNING: use "flow emulator" instead

INFO[0000] ⚙️   Using service account 0xf8d6e0586b0a20c7  serviceAddress=f8d6e0586b0a20c7 serviceHashAlgo=SHA3_256 servicePrivKey=68ee617d9bf67a4677af80aaca5a090fcda80ff2f4dbc340e0e36201fa1f1d8c servicePubKey=9cd98d436d111aab0718ab008a466d636a22ac3679d335b77e33ef7c52d9c8ce47cf5ad71ba38cedd336402aa62d5986dc224311383383c09125ec0636c0b042 serviceSigAlgo=ECDSA_P256
INFO[0003] 📜  Flow contracts                             FlowFees=0xe5a8b7f23e8b548f FlowServiceAccount=0xf8d6e0586b0a20c7 FlowStorageFees=0xf8d6e0586b0a20c7 FlowToken=0x0ae53cb6e3f42a79 FungibleToken=0xee82856bf20e2aa6
INFO[0003] 🌱  Starting gRPC server on port 3569          port=3569
INFO[0003] 🌱  Starting HTTP server on port 8080          port=8080
DEBU[0016] 👤  GetAccountAtLatestBlock called             address=f8d6e0586b0a20c7
DEBU[0016] 🎁  GetLatestBlock called                      blockHeight=0 blockID=7bc42fe85d32ca513769a74f97f7e1a7bad6c9407f0d934c2aa645ef9cf613c7
DEBU[0016] 👤  GetAccountAtLatestBlock called             address=f8d6e0586b0a20c7
DEBU[0016] ️✉️   Transaction submitted                   txID=b761076b453c95e6192536c4139069e1943a3adbb1adc4d0807b58b315ee79a2
INFO[0016] ⭐  Transaction executed                       computationUsed=3 txID=b761076b453c95e6192536c4139069e1943a3adbb1adc4d0807b58b315ee79a2
DEBU[0016] EVT [b76107] flow.AccountContractAdded: 0xa0cefb8e55952ce52d52f4f51cd21dc3034542f577dedda69e3eb64d5ee8f34a 
DEBU[0016] 📦  Block #1 committed                         blockHeight=1 blockID=f96190621c42879724f4635234b6841e704a1b03baba08839f2cf6bd6fd6b17f
DEBU[0016] 📝  GetTransactionResult called                txID=b761076b453c95e6192536c4139069e1943a3adbb1adc4d0807b58b315ee79a2
DEBU[0016] 👤  GetAccountAtLatestBlock called             address=f8d6e0586b0a20c7
DEBU[0016] 🎁  GetLatestBlock called                      blockHeight=1 blockID=f96190621c42879724f4635234b6841e704a1b03baba08839f2cf6bd6fd6b17f
DEBU[0016] 👤  GetAccountAtLatestBlock called             address=f8d6e0586b0a20c7
DEBU[0016] ️✉️   Transaction submitted                   txID=05b5cec37f5f66d5e358fc98be29553e5722c69159ad5f2639f75386b6357e60
INFO[0017] ⭐  Transaction executed                       computationUsed=8 txID=05b5cec37f5f66d5e358fc98be29553e5722c69159ad5f2639f75386b6357e60
DEBU[0017] EVT [05b5ce] A.0ae53cb6e3f42a79.FlowToken.TokensWithdrawn: 0xe39fa1017a6759f5af21e7829f5fa96533f114d3f4581d537158b7aa9b142bc3 
DEBU[0017] EVT [05b5ce] A.0ae53cb6e3f42a79.FlowToken.TokensWithdrawn: 0xa2cff7785d3b0a799b6e70574d005808ab88b7ad2c2ef037e8bb6e92e5a51aed 
DEBU[0017] EVT [05b5ce] A.0ae53cb6e3f42a79.FlowToken.TokensDeposited: 0xf332184194fcf56c6a41ec3472bfd4c633da269f7d00f1c6a7f162a89ff3d74c 
DEBU[0017] EVT [05b5ce] A.e5a8b7f23e8b548f.FlowFees.TokensDeposited: 0xcacc8d0e17a02171820685608487aac0f06700064cffdc4561f8a7b6a3b80cb0 
DEBU[0017] EVT [05b5ce] A.0ae53cb6e3f42a79.FlowToken.TokensDeposited: 0x936c13bda95a8f2ec6240fed7d90fc48b8687fc0c7946dc64c9c97b1548be09b 
DEBU[0017] EVT [05b5ce] flow.AccountCreated: 0x23446e9f8d4324f6db4f47b698a9fca9932f7eba184f62397dc939796d03bfb0 
DEBU[0017] EVT [05b5ce] flow.AccountKeyAdded: 0xa466b99ee31a6548afcf5315f686acd3595965a92a1c74394fbb4f7da355d60c 
DEBU[0017] 📦  Block #2 committed                         blockHeight=2 blockID=4266a1fdd0e46810d747877b8299d0d1bed199e2b2229eba79fad4177e12a4c0
DEBU[0017] 📝  GetTransactionResult called                txID=05b5cec37f5f66d5e358fc98be29553e5722c69159ad5f2639f75386b6357e60
DEBU[0017] 👤  GetAccountAtLatestBlock called             address=01cf0e2f2f715450
DEBU[0017] 🎁  GetLatestBlock called                      blockHeight=2 blockID=4266a1fdd0e46810d747877b8299d0d1bed199e2b2229eba79fad4177e12a4c0
DEBU[0017] 👤  GetAccountAtLatestBlock called             address=f8d6e0586b0a20c7
DEBU[0017] ️✉️   Transaction submitted                   txID=3140626bdab0e5866dfdea98c9de086e9e9916fe1e20ba5106f65b797cd95243
INFO[0017] ⭐  Transaction executed                       computationUsed=13 txID=3140626bdab0e5866dfdea98c9de086e9e9916fe1e20ba5106f65b797cd95243
DEBU[0017] LOG [314062] "Account added to ledger" 
DEBU[0017] EVT [314062] A.f8d6e0586b0a20c7.AccountManager.AccountAdded: 0xdaf9e5fcb3528c3064acd41382819e2c6f5768dde194c79ae19bd17aca922718 
DEBU[0017] 📦  Block #3 committed                         blockHeight=3 blockID=7e679edd868b557ccf9e6ad61d51461bfcf297eaaf3e4143582f081c5d5d79f8
DEBU[0017] 📝  GetTransactionResult called                txID=3140626bdab0e5866dfdea98c9de086e9e9916fe1e20ba5106f65b797cd95243
DEBU[0020] 👤  ExecuteScriptAtLatestBlock called         
INFO[0020] ⭐  Script executed                            scriptID=39f89010b17e4ff3ff14561e26cee4eff612a79ebe8fc8e57cfe4554be7829fa
DEBU[0027] 👤  GetAccountAtLatestBlock called             address=f8d6e0586b0a20c7
DEBU[0027] 🎁  GetLatestBlock called                      blockHeight=3 blockID=7e679edd868b557ccf9e6ad61d51461bfcf297eaaf3e4143582f081c5d5d79f8
DEBU[0027] 👤  GetAccountAtLatestBlock called             address=f8d6e0586b0a20c7
DEBU[0027] ️✉️   Transaction submitted                   txID=417b83c15fd15a933ab47284844d2935d23d7c17157be644b9ff4e414067eccf
INFO[0027] ⭐  Transaction executed                       computationUsed=3 txID=417b83c15fd15a933ab47284844d2935d23d7c17157be644b9ff4e414067eccf
DEBU[0027] EVT [417b83] flow.AccountContractAdded: 0x3ed281998e25633421c5d64e5c2b5b69911ef6227add29e18b77bd4e8cf98ca6 
DEBU[0027] 📦  Block #4 committed                         blockHeight=4 blockID=42d481d31846ca3663109c7cca74ff1123ecf0869391027d944213fca182ee6e
DEBU[0027] 📝  GetTransactionResult called                txID=417b83c15fd15a933ab47284844d2935d23d7c17157be644b9ff4e414067eccf
DEBU[0027] 👤  GetAccountAtLatestBlock called             address=f8d6e0586b0a20c7
DEBU[0036] 👤  GetAccountAtLatestBlock called             address=f8d6e0586b0a20c7
DEBU[0036] 👤  ExecuteScriptAtLatestBlock called         
INFO[0036] ⭐  Script executed                            scriptID=39f89010b17e4ff3ff14561e26cee4eff612a79ebe8fc8e57cfe4554be7829fa
DEBU[0041] 👤  ExecuteScriptAtLatestBlock called         
INFO[0041] ⭐  Script executed                            scriptID=39f89010b17e4ff3ff14561e26cee4eff612a79ebe8fc8e57cfe4554be7829fa
DEBU[0044] 🎁  GetLatestBlock called                      blockHeight=4 blockID=42d481d31846ca3663109c7cca74ff1123ecf0869391027d944213fca182ee6e
DEBU[0044] 👤  GetAccountAtLatestBlock called             address=01cf0e2f2f715450
DEBU[0044] ️✉️   Transaction submitted                   txID=3530df8f7f4ff71e1157db39efa1df83d76d4105a0b195dd64be389a936cc85d
INFO[0044] ⭐  Transaction executed                       computationUsed=14 txID=3530df8f7f4ff71e1157db39efa1df83d76d4105a0b195dd64be389a936cc85d
DEBU[0044] LOG [3530df] "Collection created for account 2" 
DEBU[0044] LOG [3530df] "Capability created for account 2" 
DEBU[0044] 📦  Block #5 committed                         blockHeight=5 blockID=bd8c5d089e25ab33221ba5a8e440a44c052449ea482074a9ccfca6b073ff87eb
DEBU[0044] 📝  GetTransactionResult called                txID=3530df8f7f4ff71e1157db39efa1df83d76d4105a0b195dd64be389a936cc85d
DEBU[0052] 👤  ExecuteScriptAtLatestBlock called         
WARN[0052] ❗  Script reverted                            scriptID=984b7d819f474d32495185aa8c25effde76204a7774cf73158ae9f3e9178db99
WARN[0052] ERR [984b7d] [Error Code: 1101] cadence runtime error Execution failed:
error: cannot find declaration `AccountManager` in `01cf0e2f2f715450.AccountManager`
 --> 984b7d819f474d32495185aa8c25effde76204a7774cf73158ae9f3e9178db99:2:7
  |
2 | import AccountManager from 0x01cf0e2f2f715450
  |        ^^^^^^^^^^^^^^ available exported declarations are:
 
DEBU[0075] 👤  ExecuteScriptAtLatestBlock called         
WARN[0075] ❗  Script reverted                            scriptID=984b7d819f474d32495185aa8c25effde76204a7774cf73158ae9f3e9178db99
WARN[0075] ERR [984b7d] [Error Code: 1101] cadence runtime error Execution failed:
error: cannot find declaration `AccountManager` in `01cf0e2f2f715450.AccountManager`
 --> 984b7d819f474d32495185aa8c25effde76204a7774cf73158ae9f3e9178db99:2:7
  |
2 | import AccountManager from 0x01cf0e2f2f715450
  |        ^^^^^^^^^^^^^^ available exported declarations are:
 
DEBU[0085] 👤  ExecuteScriptAtLatestBlock called         
WARN[0085] ❗  Script reverted                            scriptID=984b7d819f474d32495185aa8c25effde76204a7774cf73158ae9f3e9178db99
WARN[0085] ERR [984b7d] [Error Code: 1101] cadence runtime error Execution failed:
error: cannot find declaration `AccountManager` in `01cf0e2f2f715450.AccountManager`
 --> 984b7d819f474d32495185aa8c25effde76204a7774cf73158ae9f3e9178db99:2:7
  |
2 | import AccountManager from 0x01cf0e2f2f715450
  |        ^^^^^^^^^^^^^^ available exported declarations are:

:
### Acceptance Criteria

If this Cadence plugin issue will fix I can possibility continue check my Flow Contract

### Context

I'm working on new Flow Contract for new NFT Gallery based on Flow blockchain . I can't review my Contract due I can't use more than one account to check all capabilities

**Comment by MaxStalker** [comment]
@mrakus7 I found where this is happening and currently working on a fix for this and related problems :)

**Comment by MaxStalker** [comment]
@mrakus7 We've identified the problem and prepared a fix for language server here:
https://github.com/onflow/cadence/pull/1295/

Now you can wait for new release for CLI (which bundles language server) or you can:
- fetch cadence repo (https://github.com/onflow/cadence/pull/1295/)
- update `Flow Command` in your VS Code with absolute path to `run.sh` script in language server folder (https://github.com/onflow/cadence/blob/master/languageserver/run.sh)
- restart language server

You will need proper Golang setup if you would to go second route :)

**Comment by kerrywei** [comment]
update: 
pending CI pipeline to be fixed before PR https://github.com/onflow/cadence/pull/1295 to be merged in

**Comment by kerrywei** [comment]
note: we need release language server + CLI to reflect the update

**Comment by kerrywei** [comment]
FCL will be updated on Dec 15 so that vs code extension should be fully fixed

**Comment by kerrywei** [comment]
Both @MaxStalker and I verified the newer version of flow-cli 0.30.1 addressed this issue. 
Huge thanks to @MaxStalker for driving the fix!
