### ISSUE TITLE
vscode-cadence cannot run on Windows

### ISSUE THREAD

**Issue by Bamthelearner** [onflow/vscode-cadence#74]
### Problem
When vscode-cadence is ran on Windows vscode, the extension will crash due to wrong path.

Is it possible to solve this and help better the development experience?

Currently I am using wsl for developing.
![image](https://user-images.githubusercontent.com/95492891/159155846-6ef3184c-a1d2-46db-9294-b693e9158a12.png)

**Comment by Pure-Peace** [comment]
the same issues #57 

solution #67  was committed last Sep, and somehow it hasn't been merged into the master branch?
