### ISSUE TITLE
[Docs Site] Landing Page

### ISSUE THREAD

**Issue by 10thfloor** [onflow/vscode-cadence#82]
Finish the landing page including dynamic components.
Figma design: https://www.figma.com/proto/jxzg0xbPBLbWz2BFsFPPx1/Prototypes?node-id=1654%3A22500&scaling=min-zoom&page-id=1429%3A21963&starting-point-node-id=1654%3A22500

**Comment by kerrywei** [comment]
@10thfloor should this issue belong to a different repo? we should move or close this one
