### ISSUE TITLE
Release Latest version on Marketplace

### ISSUE THREAD

**Issue by MaxStalker** [onflow/vscode-cadence#88]
### Problem

There are several issues reported by users on Windows platform related to the config path, when starting up emulator.
This PR from last year is solving the issue - https://github.com/onflow/vscode-cadence/pull/67 - and it was already merged into main branch. But updated code was not released on [Visual Studio Code Marketplace](https://marketplace.visualstudio.com/VSCode).

**Comment by AlmostEfficient** [comment]
This is still an issue on 0.7.0, which was published to the marketplace earlier today. From the looks of it, your PR was merged into its [own branch](https://github.com/onflow/vscode-cadence/tree/submissions/issue-3/koala), not main. 

Main/marketplace (0.7.0) is still using `path` in this one spot:
![image](https://user-images.githubusercontent.com/42661870/174002588-b427a5ac-b279-443b-9b42-bf05635e6281.png)

https://github.com/onflow/vscode-cadence/blob/master/src/config.ts#L42

I built 0.6.4, installed it manually, and it worked whereas 0.7.0 did not.

**Comment by DylanTinianov** [comment]
Released
